// src/utils/advancedNumericFilters.js
export default [
  { field: "overall_stats", label: "OVR" },
  { field: "age", label: "Age" },
  { field: "height", label: "Height" },
  { field: "weight", label: "Weight" },
  { field: "weak_foot_usage", label: "Weak Foot Usage" },
  { field: "weak_foot_accuracy", label: "Weak Foot Accuracy" },
  { field: "form", label: "Form" },
  { field: "injury_resistance", label: "Injury Resistance" },
  { field: "offensive_awareness", label: "Offensive Awareness" },
  { field: "ball_control", label: "Ball Control" },
  { field: "dribbling", label: "Dribbling" },
  { field: "tight_possession", label: "Tight Possession" },
  { field: "low_pass", label: "Low Pass" },
  { field: "lofted_pass", label: "Lofted Pass" },
  { field: "finishing", label: "Finishing" },
  { field: "heading", label: "Heading" },
  { field: "place_kicking", label: "Place Kicking" },
  { field: "curl", label: "Curl" },
  { field: "speed", label: "Speed" },
  { field: "acceleration", label: "Acceleration" },
  { field: "kicking_power", label: "Kicking Power" },
  { field: "jump", label: "Jump" },
  { field: "physical_contact", label: "Physical Contact" },
  { field: "balance", label: "Balance" },
  { field: "stamina", label: "Stamina" },
  { field: "defensive_awareness", label: "Defensive Awareness" },
  { field: "ball_winning", label: "Ball Winning" },
  { field: "aggression", label: "Aggression" },
  // GK Stats
  { field: "gk_awareness", label: "GK Awareness" },
  { field: "gk_catching", label: "GK Catching" },
  { field: "gk_clearing", label: "GK Clearing" },
  { field: "gk_reflexes", label: "GK Reflexes" },
  { field: "gk_reach", label: "GK Reach" },
];
