// src/utils/advancedBooleanFilters.js
export default [
  { field: "trickster", label: "Trickster" },
  { field: "mazing_run", label: "Mazing Run" },
  { field: "speeding_bullet", label: "Speeding Bullet" },
  { field: "incisive_run", label: "Incisive Run" },
  { field: "long_ball_expert", label: "Long Ball Expert" },
  { field: "early_cross", label: "Early Cross" },
  { field: "long_ranger", label: "Long Ranger" },
  { field: "scissors_feint", label: "Scissors Feint" },
  { field: "double_touch", label: "Double Touch" },
  { field: "flip_flap", label: "Flip Flap" },
  { field: "marseille_turn", label: "Marseille Turn" },
  { field: "sombrero", label: "Sombrero" },
  { field: "cross_over_turn", label: "Cross Over Turn" },
  { field: "cut_behind_and_turn", label: "Cut Behind and Turn" },
  { field: "scotch_move", label: "Scotch Move" },
  { field: "step_on_skillcontrol", label: "Step on Skillcontrol" },
  { field: "heading_special", label: "Heading Special" },
  { field: "long_range_drive", label: "Long Range Drive" },
  { field: "chipshot_control", label: "Chipshot Control" },
  { field: "long_range_shot", label: "Long Range Shot" },
  { field: "knuckle_shot", label: "Knuckle Shot" },
  { field: "dipping_shots", label: "Dipping Shots" },
  { field: "rising_shots", label: "Rising Shots" },
  { field: "acrobatic_finishing", label: "Acrobatic Finishing" },
  { field: "heel_trick", label: "Heel Trick" },
  { field: "first_time_shot", label: "First Time Shot" },
  { field: "one_touch_pass", label: "One Touch Pass" },
  { field: "through_passing", label: "Through Passing" },
  { field: "weighted_pass", label: "Weighted Pass" },
  { field: "pinpoint_crossing", label: "Pinpoint Crossing" },
  { field: "outside_curler", label: "Outside Curler" },
  { field: "rabona", label: "Rabona" },
  { field: "no_look_pass", label: "No Look Pass" },
  { field: "low_lofted_pass", label: "Low Lofted Pass" },
  { field: "gk_low_punt", label: "GK Low Punt" },
  { field: "gk_high_punt", label: "GK High Punt" },
  { field: "long_throw", label: "Long Throw" },
  { field: "gk_long_throw", label: "GK Long Throw" },
  { field: "penalty_specialist", label: "Penalty Specialist" },
  { field: "gk_penalty_saver", label: "GK Penalty Saver" },
  { field: "gamesmanship", label: "Gamesmanship" },
  { field: "man_marking", label: "Man Marking" },
  { field: "track_back", label: "Track Back" },
  { field: "interception", label: "Interception" },
  { field: "acrobatic_clear", label: "Acrobatic Clear" },
  { field: "captaincy", label: "Captaincy" },
  { field: "super_sub", label: "Super Sub" },
  { field: "fighting_spirit", label: "Fighting Spirit" },
];
