"""Add Standing model fix

Revision ID: 0a724f5a6fb1
Revises: 8ada46a8c842
Create Date: 2025-04-14 22:56:59.647748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a724f5a6fb1'
down_revision: Union[str, None] = '8ada46a8c842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_standings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('played', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('won', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('drawn', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('goal_difference', sa.Integer(), nullable=True))
        batch_op.drop_column('draws')
        batch_op.drop_column('wins')
        batch_op.drop_column('matches_played')
        batch_op.drop_column('losses')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league_standings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('losses', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('matches_played', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('wins', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('draws', sa.INTEGER(), nullable=True))
        batch_op.drop_column('goal_difference')
        batch_op.drop_column('lost')
        batch_op.drop_column('drawn')
        batch_op.drop_column('won')
        batch_op.drop_column('played')

    # ### end Alembic commands ###
