"""Add competition field to match model

Revision ID: 2a7c0a6e033b
Revises: 404bcf2ee049
Create Date: 2025-04-13 20:37:33.716552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7c0a6e033b'
down_revision: Union[str, None] = '404bcf2ee049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('competition', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'competition')
    # ### end Alembic commands ###
