"""Add LeagueStanding model

Revision ID: 36f2fbb65016
Revises: 12cfbe1da4cf
Create Date: 2025-04-14 22:35:36.136852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f2fbb65016'
down_revision: Union[str, None] = '12cfbe1da4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
