"""Initial DB schema

Revision ID: db4f509b8bcd
Revises: 
Create Date: 2025-04-12 22:52:56.551260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4f509b8bcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_id'), 'admin_logs', ['id'], unique=False)
    op.create_table('clubs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_controlled_by_player', sa.Boolean(), nullable=True),
    sa.Column('league', sa.String(), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('stadium_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('manager_name', sa.String(), nullable=True),
    sa.Column('trophies_won', sa.Integer(), nullable=True),
    sa.Column('transfer_budget', sa.Float(), nullable=True),
    sa.Column('wage_budget', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_clubs_id'), 'clubs', ['id'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('current_matchday', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_seasons_id'), 'seasons', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('finances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('expenses', sa.Float(), nullable=True),
    sa.Column('salary_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id')
    )
    op.create_index(op.f('ix_finances_id'), 'finances', ['id'], unique=False)
    op.create_table('matchdays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchdays_id'), 'matchdays', ['id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('foot', sa.String(), nullable=True),
    sa.Column('overall_stats', sa.Integer(), nullable=True),
    sa.Column('market_value', sa.Float(), nullable=True),
    sa.Column('wage', sa.Float(), nullable=True),
    sa.Column('offensive_awareness', sa.Integer(), nullable=True),
    sa.Column('ball_control', sa.Integer(), nullable=True),
    sa.Column('dribbling', sa.Integer(), nullable=True),
    sa.Column('tight_possession', sa.Integer(), nullable=True),
    sa.Column('low_pass', sa.Integer(), nullable=True),
    sa.Column('lofted_pass', sa.Integer(), nullable=True),
    sa.Column('finishing', sa.Integer(), nullable=True),
    sa.Column('heading', sa.Integer(), nullable=True),
    sa.Column('place_kicking', sa.Integer(), nullable=True),
    sa.Column('curl', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('acceleration', sa.Integer(), nullable=True),
    sa.Column('kicking_power', sa.Integer(), nullable=True),
    sa.Column('jump', sa.Integer(), nullable=True),
    sa.Column('physical_contact', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('stamina', sa.Integer(), nullable=True),
    sa.Column('defensive_awareness', sa.Integer(), nullable=True),
    sa.Column('ball_winning', sa.Integer(), nullable=True),
    sa.Column('aggression', sa.Integer(), nullable=True),
    sa.Column('weak_foot_usage', sa.Integer(), nullable=True),
    sa.Column('weak_foot_accuracy', sa.Integer(), nullable=True),
    sa.Column('form', sa.Integer(), nullable=True),
    sa.Column('injury_resistance', sa.Integer(), nullable=True),
    sa.Column('gk_awareness', sa.Integer(), nullable=True),
    sa.Column('gk_catching', sa.Integer(), nullable=True),
    sa.Column('gk_clearing', sa.Integer(), nullable=True),
    sa.Column('gk_reflexes', sa.Integer(), nullable=True),
    sa.Column('gk_reach', sa.Integer(), nullable=True),
    sa.Column('trickster', sa.Boolean(), nullable=True),
    sa.Column('mazing_run', sa.Boolean(), nullable=True),
    sa.Column('speeding_bullet', sa.Boolean(), nullable=True),
    sa.Column('incisive_run', sa.Boolean(), nullable=True),
    sa.Column('long_ball_expert', sa.Boolean(), nullable=True),
    sa.Column('early_cross', sa.Boolean(), nullable=True),
    sa.Column('long_ranger', sa.Boolean(), nullable=True),
    sa.Column('scissors_feint', sa.Boolean(), nullable=True),
    sa.Column('double_touch', sa.Boolean(), nullable=True),
    sa.Column('flip_flap', sa.Boolean(), nullable=True),
    sa.Column('marseille_turn', sa.Boolean(), nullable=True),
    sa.Column('sombrero', sa.Boolean(), nullable=True),
    sa.Column('cross_over_turn', sa.Boolean(), nullable=True),
    sa.Column('cut_behind_and_turn', sa.Boolean(), nullable=True),
    sa.Column('scotch_move', sa.Boolean(), nullable=True),
    sa.Column('step_on_skillcontrol', sa.Boolean(), nullable=True),
    sa.Column('heading_special', sa.Boolean(), nullable=True),
    sa.Column('long_range_drive', sa.Boolean(), nullable=True),
    sa.Column('chipshot_control', sa.Boolean(), nullable=True),
    sa.Column('long_range_shot', sa.Boolean(), nullable=True),
    sa.Column('knuckle_shot', sa.Boolean(), nullable=True),
    sa.Column('dipping_shots', sa.Boolean(), nullable=True),
    sa.Column('rising_shots', sa.Boolean(), nullable=True),
    sa.Column('acrobatic_finishing', sa.Boolean(), nullable=True),
    sa.Column('heel_trick', sa.Boolean(), nullable=True),
    sa.Column('first_time_shot', sa.Boolean(), nullable=True),
    sa.Column('one_touch_pass', sa.Boolean(), nullable=True),
    sa.Column('through_passing', sa.Boolean(), nullable=True),
    sa.Column('weighted_pass', sa.Boolean(), nullable=True),
    sa.Column('pinpoint_crossing', sa.Boolean(), nullable=True),
    sa.Column('outside_curler', sa.Boolean(), nullable=True),
    sa.Column('rabona', sa.Boolean(), nullable=True),
    sa.Column('no_look_pass', sa.Boolean(), nullable=True),
    sa.Column('low_lofted_pass', sa.Boolean(), nullable=True),
    sa.Column('gk_low_punt', sa.Boolean(), nullable=True),
    sa.Column('gk_high_punt', sa.Boolean(), nullable=True),
    sa.Column('long_throw', sa.Boolean(), nullable=True),
    sa.Column('gk_long_throw', sa.Boolean(), nullable=True),
    sa.Column('penalty_specialist', sa.Boolean(), nullable=True),
    sa.Column('gk_penalty_saver', sa.Boolean(), nullable=True),
    sa.Column('gamesmanship', sa.Boolean(), nullable=True),
    sa.Column('man_marking', sa.Boolean(), nullable=True),
    sa.Column('track_back', sa.Boolean(), nullable=True),
    sa.Column('interception', sa.Boolean(), nullable=True),
    sa.Column('acrobatic_clear', sa.Boolean(), nullable=True),
    sa.Column('captaincy', sa.Boolean(), nullable=True),
    sa.Column('super_sub', sa.Boolean(), nullable=True),
    sa.Column('fighting_spirit', sa.Boolean(), nullable=True),
    sa.Column('gk', sa.String(), nullable=True),
    sa.Column('cb', sa.String(), nullable=True),
    sa.Column('lb', sa.String(), nullable=True),
    sa.Column('rb', sa.String(), nullable=True),
    sa.Column('dmf', sa.String(), nullable=True),
    sa.Column('cmf', sa.String(), nullable=True),
    sa.Column('lmf', sa.String(), nullable=True),
    sa.Column('rmf', sa.String(), nullable=True),
    sa.Column('amf', sa.String(), nullable=True),
    sa.Column('lwf', sa.String(), nullable=True),
    sa.Column('rwf', sa.String(), nullable=True),
    sa.Column('ss', sa.String(), nullable=True),
    sa.Column('cf', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('pes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_index(op.f('ix_players_pes_id'), 'players', ['pes_id'], unique=True)
    op.create_table('tactics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_id', sa.Integer(), nullable=True),
    sa.Column('formation', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('club_id')
    )
    op.create_index(op.f('ix_tactics_id'), 'tactics', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('home_club_id', sa.Integer(), nullable=True),
    sa.Column('away_club_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('matchday_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['home_club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchdays.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('training',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_id'), 'training', ['id'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('from_club_id', sa.Integer(), nullable=True),
    sa.Column('to_club_id', sa.Integer(), nullable=False),
    sa.Column('transfer_fee', sa.Integer(), nullable=True),
    sa.Column('transfer_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_club_id'], ['clubs.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['to_club_id'], ['clubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transfers_id'), 'transfers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfers_id'), table_name='transfers')
    op.drop_table('transfers')
    op.drop_index(op.f('ix_training_id'), table_name='training')
    op.drop_table('training')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_tactics_id'), table_name='tactics')
    op.drop_table('tactics')
    op.drop_index(op.f('ix_players_pes_id'), table_name='players')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matchdays_id'), table_name='matchdays')
    op.drop_table('matchdays')
    op.drop_index(op.f('ix_finances_id'), table_name='finances')
    op.drop_table('finances')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_seasons_id'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_clubs_id'), table_name='clubs')
    op.drop_table('clubs')
    op.drop_index(op.f('ix_admin_logs_id'), table_name='admin_logs')
    op.drop_table('admin_logs')
    # ### end Alembic commands ###
