from sqlalchemy import Column, Integer, String, Float, Boolean, ForeignKey, DateTime, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
from .base import Base

class Player(Base):
    __tablename__ = "players"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, nullable=False)
    country = Column(String)
    height = Column(Float)
    weight = Column(Float)
    age = Column(Integer)
    foot = Column(String)
    overall_stats = Column(Integer)
    market_value = Column(Float)
    wage = Column(Float)

    # Core Attributes
    offensive_awareness = Column(Integer)
    ball_control = Column(Integer)
    dribbling = Column(Integer)
    tight_possession = Column(Integer)
    low_pass = Column(Integer)
    lofted_pass = Column(Integer)
    finishing = Column(Integer)
    heading = Column(Integer)
    place_kicking = Column(Integer)
    curl = Column(Integer)
    speed = Column(Integer)
    acceleration = Column(Integer)
    kicking_power = Column(Integer)
    jump = Column(Integer)
    physical_contact = Column(Integer)
    balance = Column(Integer)
    stamina = Column(Integer)
    defensive_awareness = Column(Integer)
    ball_winning = Column(Integer)
    aggression = Column(Integer)
    weak_foot_usage = Column(Integer)
    weak_foot_accuracy = Column(Integer)
    form = Column(Integer)
    injury_resistance = Column(Integer)


    # GK Stats
    gk_awareness = Column(Integer)
    gk_catching = Column(Integer)
    gk_clearing = Column(Integer)
    gk_reflexes = Column(Integer)
    gk_reach = Column(Integer)

    # Traits
    # Skill booleans (default=False)
    trickster = Column(Boolean, default=False)
    mazing_run = Column(Boolean, default=False)
    speeding_bullet = Column(Boolean, default=False)
    incisive_run = Column(Boolean, default=False)
    long_ball_expert = Column(Boolean, default=False)
    early_cross = Column(Boolean, default=False)
    long_ranger = Column(Boolean, default=False)
    scissors_feint = Column(Boolean, default=False)
    double_touch = Column(Boolean, default=False)
    flip_flap = Column(Boolean, default=False)
    marseille_turn = Column(Boolean, default=False)
    sombrero = Column(Boolean, default=False)
    cross_over_turn = Column(Boolean, default=False)
    cut_behind_and_turn = Column(Boolean, default=False)
    scotch_move = Column(Boolean, default=False)
    step_on_skillcontrol = Column(Boolean, default=False)
    heading_special = Column(Boolean, default=False)
    long_range_drive = Column(Boolean, default=False)
    chipshot_control = Column(Boolean, default=False)
    long_range_shot = Column(Boolean, default=False)
    knuckle_shot = Column(Boolean, default=False)
    dipping_shots = Column(Boolean, default=False)
    rising_shots = Column(Boolean, default=False)
    acrobatic_finishing = Column(Boolean, default=False)
    heel_trick = Column(Boolean, default=False)
    first_time_shot = Column(Boolean, default=False)
    one_touch_pass = Column(Boolean, default=False)
    through_passing = Column(Boolean, default=False)
    weighted_pass = Column(Boolean, default=False)
    pinpoint_crossing = Column(Boolean, default=False)
    outside_curler = Column(Boolean, default=False)
    rabona = Column(Boolean, default=False)
    no_look_pass = Column(Boolean, default=False)
    low_lofted_pass = Column(Boolean, default=False)
    gk_low_punt = Column(Boolean, default=False)
    gk_high_punt = Column(Boolean, default=False)
    long_throw = Column(Boolean, default=False)
    gk_long_throw = Column(Boolean, default=False)
    penalty_specialist = Column(Boolean, default=False)
    gk_penalty_saver = Column(Boolean, default=False)
    gamesmanship = Column(Boolean, default=False)
    man_marking = Column(Boolean, default=False)
    track_back = Column(Boolean, default=False)
    interception = Column(Boolean, default=False)
    acrobatic_clear = Column(Boolean, default=False)
    captaincy = Column(Boolean, default=False)
    super_sub = Column(Boolean, default=False)
    fighting_spirit = Column(Boolean, default=False)


    # Positional Proficiency (string fields for now)
    gk = Column(String)
    cb = Column(String)
    lb = Column(String)
    rb = Column(String)
    dmf = Column(String)
    cmf = Column(String)
    lmf = Column(String)
    rmf = Column(String)
    amf = Column(String)
    lwf = Column(String)
    rwf = Column(String)
    ss = Column(String)
    cf = Column(String)

    # Positional Proficiency (JSON object, e.g. {"gk": true, "cb": false, ...})
    positions = Column(JSON, default=dict)

    # Timestamps
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow)

    # Club (nullable FK)
    club_id = Column(Integer, ForeignKey("clubs.id"), nullable=True)
    club = relationship("Club", back_populates="players")
    transfers = relationship("Transfer", back_populates="player")
    pes_id = Column(Integer, unique=True, index=True)



